version: '3.8'
services:
  db:
    image: postgis/postgis:15-3.3
    container_name: tapak-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tapakpassword
      POSTGRES_DB: tapak
    ports:
      - "5432:5432"
    volumes:
      - tapak_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  tapak_pgdata:
