import { ListingItem } from "./types";

export const MOCK_LISTINGS: ListingItem[] = [
  {
    id: "tap-001",
    title: "The Pakubuwono Signature 3BR Full Furnished",
    slug: "the-pakubuwono-signature-3br-full-furnished",
    description:
      "Hunian vertikal mewah di Kebayoran Baru dengan pemandangan cakrawala kota 360 derajat. Dilengkapi interior berstandar internasional, dapur marmer desainer, lift privat langsung ke unit, serta fasilitas klub olahraga bintang lima. Unit ini telah diverifikasi penuh oleh tim kurator Tapak. mencakup legalitas sertifikat hak milik dan inspeksi struktural.",
    price: 45000000,
    deposit: 45000000,
    maintenance_fee: 3800000,
    utility_estimate: 2500000,
    verification_tier: "GOLD",
    property_type: "Apartemen",
    bedrooms: 3,
    bathrooms: 3,
    area_sqm: 185,
    address: "Jl. Pakubuwono VI No. 72, Gunung",
    district: "Kebayoran Baru",
    city: "Jakarta Selatan",
    latitude: -6.2368,
    longitude: 106.7909,
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
    ],
    amenities: [
      "Private Lift",
      "Kolam Renang Infinity",
      "Gym & Pilates Studio",
      "Keamanan 24 Jam & Biometrik",
      "Parkir Dedicated (2 Slot)",
      "Balkon Luas",
      "Dapur Marmer Premium",
      "AC Central Inverter",
    ],
    is_available: true,
    agent_name: "Bambang Sudibyo",
    agent_phone: "6281288991122",
  },
  {
    id: "tap-002",
    title: "Modern Minimalist Villa Sanur Tropical Sanctuary",
    slug: "modern-minimalist-villa-sanur-tropical-sanctuary",
    description:
      "Vila tropis modern 5 menit berjalan kaki ke pantai Sanur. Desain arsitektur semi-terbuka dengan sirkulasi udara optimal, kolam renang pribadi, taman tropis terawat, serta sistem solar panel terintegrasi. Verifikasi status kepemilikan dan perizinan IMB komersial siap pakai.",
    price: 32000000,
    deposit: 30000000,
    maintenance_fee: 2000000,
    utility_estimate: 1800000,
    verification_tier: "GOLD",
    property_type: "Vila",
    bedrooms: 2,
    bathrooms: 2,
    area_sqm: 220,
    address: "Jl. Danau Tamblingan No. 88, Sanur Kauh",
    district: "Sanur",
    city: "Denpasar",
    latitude: -8.6987,
    longitude: 115.2618,
    images: [
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80",
    ],
    amenities: [
      "Private Swimming Pool",
      "Lush Garden",
      "Smart Home Automation",
      "High-speed Fiber Optic",
      "Carport 2 Mobil",
      "Fully Furnished Teak Wood",
    ],
    is_available: true,
    agent_name: "Ni Putu Dewi",
    agent_phone: "6281934567890",
  },
  {
    id: "tap-003",
    title: "District 8 SCBD Studio Suite High Floor",
    slug: "district-8-scbd-studio-suite-high-floor",
    description:
      "Studio eksklusif di jantung kawasan finansial Sudirman Central Business District (SCBD). Lokasi premium dengan akses pejalan kaki ke Ashta Mall, Pacific Place, dan stasiun MRT Istora Mandiri. Pilihan ideal untuk ekspatriat maupun profesional muda.",
    price: 18500000,
    deposit: 18500000,
    maintenance_fee: 1450000,
    utility_estimate: 1100000,
    verification_tier: "SILVER",
    property_type: "Apartemen",
    bedrooms: 1,
    bathrooms: 1,
    area_sqm: 48,
    address: "District 8 Senopati, Jl. Jend. Sudirman Kav. 52-53",
    district: "Senayan / SCBD",
    city: "Jakarta Selatan",
    latitude: -6.2274,
    longitude: 106.8087,
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
    ],
    amenities: [
      "Akses Langsung ke Ashta Mall",
      "Gym Sky Lounge",
      "Kolam Renang Semi-Olympic",
      "Concierge 24 Jam",
      "Smart Card Access",
    ],
    is_available: true,
    agent_name: "Arya Wibawa",
    agent_phone: "6281112223344",
  },
  {
    id: "tap-004",
    title: "Rumah Sudut Arsitektur Skandinavia Navapark BSD",
    slug: "rumah-sudut-arsitektur-skandinavia-navapark-bsd",
    description:
      "Hunian tapak 2 lantai berkonsep resort di kawasan bergengsi Navapark BSD City. Menghadap langsung ke Botanical Park seluas 10 hektar. Memiliki ceiling setinggi 4.2 meter, pencahayaan alami melimpah, dan sistem keamanan triple gate yang terpercaya.",
    price: 28000000,
    deposit: 25000000,
    maintenance_fee: 1650000,
    utility_estimate: 1750000,
    verification_tier: "GOLD",
    property_type: "Rumah",
    bedrooms: 4,
    bathrooms: 3,
    area_sqm: 240,
    address: "Cluster Lancewood, Navapark BSD",
    district: "Serpong",
    city: "Tangerang Selatan",
    latitude: -6.3039,
    longitude: 106.6534,
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1200&q=80",
    ],
    amenities: [
      "Clubhouse Resort 3.5 Ha",
      "Underground Cable System",
      "Taman Belakang Pribadi",
      "Garasi 2 Mobil + Canopy",
      "Solar Water Heater",
      "Triple Gate Security",
    ],
    is_available: true,
    agent_name: "Clara Tanuwidjaja",
    agent_phone: "6281344556677",
  },
  {
    id: "tap-005",
    title: "Casa Verde Setiabudi Executive Loft 2BR",
    slug: "casa-verde-setiabudi-executive-loft-2br",
    description:
      "Apartemen mezzanine loft unik di Setiabudi. Desain industrial hangat dengan aksen bata ekspos dan kayu solid. Sangat dekat dengan pusat kuliner Rasuna Said dan stasiun LRT Dukuh Atas. Biaya IPL dan utilitas sangat terukur dan transparan.",
    price: 15000000,
    deposit: 15000000,
    maintenance_fee: 950000,
    utility_estimate: 950000,
    verification_tier: "BRONZE",
    property_type: "Apartemen",
    bedrooms: 2,
    bathrooms: 1,
    area_sqm: 64,
    address: "Jl. Setiabudi Tengah No. 14",
    district: "Setiabudi",
    city: "Jakarta Selatan",
    latitude: -6.2118,
    longitude: 106.8285,
    images: [
      "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80",
    ],
    amenities: [
      "Mezzanine High Ceiling",
      "Kitchen Island",
      "Work From Home Corner",
      "Rooftop Garden",
      "High-speed Internet Ready",
    ],
    is_available: true,
    agent_name: "Reza Rahardian",
    agent_phone: "6281778899001",
  },
  {
    id: "tap-006",
    title: "Kost Eksklusif Senopati Co-Living Suite",
    slug: "kost-eksklusif-senopati-co-living-suite",
    description:
      "Kamar hunian privat dengan standar hotel butik di kawasan hits Senopati. Sudah termasuk pembersihan kamar mingguan, penggantian sprei berkala, dan akses dapur bersama serbaguna. Parkir mobil dan motor tersedia dengan gate RFID.",
    price: 6500000,
    deposit: 3000000,
    maintenance_fee: 350000,
    utility_estimate: 450000,
    verification_tier: "SILVER",
    property_type: "Kost",
    bedrooms: 1,
    bathrooms: 1,
    area_sqm: 24,
    address: "Jl. Suryo No. 42, Senopati",
    district: "Kebayoran Baru",
    city: "Jakarta Selatan",
    latitude: -6.2341,
    longitude: 106.8142,
    images: [
      "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1200&q=80",
    ],
    amenities: [
      "Kamar Mandi Dalam & Water Heater",
      "Smart TV 43 inch",
      "Housekeeping Mingguan",
      "Dapur Komunal Lengkap",
      "Kunci Pintu Digital Card",
    ],
    is_available: true,
    agent_name: "Dina Mariana",
    agent_phone: "6281556677889",
  },
  {
    id: "tap-007",
    title: "Ruko Komersial 3.5 Lantai Boulevard Gading Serpong",
    slug: "ruko-komersial-3-5-lantai-boulevard-gading-serpong",
    description:
      "Ruko strategis di jalan utama Boulevard Gading Serpong dengan lalu lintas padat 24 jam. Sangat cocok untuk kantor arsitek, klinik estetika, cafe bertema, maupun lembaga kursus. Dilengkapi parkir on-street leluasa dan lift barang.",
    price: 35000000,
    deposit: 35000000,
    maintenance_fee: 1200000,
    utility_estimate: 2800000,
    verification_tier: "SILVER",
    property_type: "Ruko",
    bedrooms: 3,
    bathrooms: 3,
    area_sqm: 210,
    address: "Boulevard Raya Gading Serpong Blok AA No. 12",
    district: "Kelapa Dua",
    city: "Tangerang",
    latitude: -6.2425,
    longitude: 106.6289,
    images: [
      "https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
    ],
    amenities: [
      "Lokasi Hadap Jalan Utama",
      "Area Parkir Luas",
      "Listrik 11.000 VA",
      "Instalasi Jalur AC Ready",
      "Kaca Tempered Depan",
    ],
    is_available: true,
    agent_name: "Hendrik Wijaya",
    agent_phone: "6281188223344",
  },
  {
    id: "tap-008",
    title: "Ciputra World 2 Jakarta Orchard Satrio 2BR",
    slug: "ciputra-world-2-jakarta-orchard-satrio-2br",
    description:
      "Apartemen prestisius di koridor emas Prof. Dr. Satrio (Mega Kuningan). Akses langsung ke Lotte Shopping Avenue dan stasiun LRT Kuningan. Dilengkapi fasilitas kolam renang bernuansa taman tropis pulau dewata, lapangan tenis, dan gym modern.",
    price: 22000000,
    deposit: 22000000,
    maintenance_fee: 1900000,
    utility_estimate: 1500000,
    verification_tier: "GOLD",
    property_type: "Apartemen",
    bedrooms: 2,
    bathrooms: 2,
    area_sqm: 98,
    address: "Jl. Prof. DR. Satrio No.Kav 11, Karet Semanggi",
    district: "Mega Kuningan",
    city: "Jakarta Selatan",
    latitude: -6.2223,
    longitude: 106.8228,
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80",
    ],
    amenities: [
      "Direct Bridge to Lotte Avenue",
      "Lap Tennis Court",
      "Jacuzzi & Sauna",
      "Children Playground",
      "Dedicated Basement Parking",
    ],
    is_available: true,
    agent_name: "Bambang Sudibyo",
    agent_phone: "6281288991122",
  },
];
